version: '3.2'

services:
 

  app:
    build: .
    command: npm start
    volumes:
      - .:/app
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: test
    ports:
      - "3333:3333"
    depends_on:
      - db
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: myapp
    volumes:
      - db-data:/var/lib/mysql  
    ports:
      - "3306:3306"
    
volumes:
  db-data: